# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rideau-canal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build

      - name: Package deployment artifacts
        run: |
          mkdir -p deploy-output
          cp -r dist deploy-output/
          cp server.js deploy-output/
          cp package.json deploy-output/
          cp package-lock.json deploy-output/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy-output/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E99AB991668C42FE902398E7ABCC6B79 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_777EC8039ED8474895DFE93BFC7EF344 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3BD5B8C5FFCB439D947EF48529F3814E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'rideau-canal'
          slot-name: 'Production'
          package: .
          